@'
upstream api_gateway_backend {
    server api-gateway-1:8080;
    server api-gateway-2:8081;
    server api-gateway-3:8082;
}

server {
    listen 80;
    
    location / {
        proxy_pass http://api_gateway_backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
    
    location /health {
        return 200 'OK';
        add_header Content-Type text/plain;
    }
}
'@ | Out-File -FilePath D:\CODE\event_mang_hackathon\load-balancer\nginx.conf -Encoding utf8 -Force